spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/octo_test?createDatabaseIfNotExist=true
    username: root
    password: ""
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDB103Dialect
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port: 8181